kind: Deployment
apiVersion: apps/v1
metadata:
  name: apache-declarative-deployment
spec:
  replicas: 5             # total no. of pod to be created
  selector:                   # tell pod name whose relplica should be 2
    matchLabels: 
      app: declarative-apache
  template: 
    metadata:
      name: apache-declarative-deployment-pod   #name of pod
      labels:
        app: declarative-apache

    spec:
      containers:
      - name: apache
        image: httpd:latest
        ports:
        - containerPort: 80

   
